# Generated by Django 5.0.2 on 2024-03-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'car_ads',
            },
        ),
    ]
